CREATE DATABASE TEST_DB;
GRANT ALL PRIVILEGES ON TEST_DB.* TO 'test@localhost' IDENTIFIED BY 'test';
FLUSH PRIVILEGES;

USE TEST_DB;
CREATE TABLE T_USER
(
    USER_ID VARCHAR(30) NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    AGE     INTEGER,
    ADDRESS VARCHAR(200),
    INSERT_DATE TIMESTAMP,
    CONSTRAINT PRIMARY KEY (USER_ID)
);
